### ISSUE TITLE
Lỗi khi cài đặt bản thủ công

### ISSUE THREAD

**Issue by phuleethanh** [natsukagami/kjudge#16]
Chào bạn, khi mình cài đặt bản thủ công, đến bước cuối cùng gặp lỗi không get được thư mục kjudge/statics. Bạn có thể thêm thư mục này vào hithub được không? Xin cảm ơn

**Comment by natsukagami** [comment]
Cho mình hỏi lỗi cụ thể như nào nhỉ? Vì kjudge hoàn toàn không có thư mục nào tên là `kjudge/statics` cả.

**Comment by phuleethanh** [comment]
![Screen Capture_deepin-terminal_20200511062722](https://user-images.githubusercontent.com/24895255/81513204-de08b200-9350-11ea-9967-7fcb35def9c1.png)
![Screen Capture_deepin-terminal_20200511062842](https://user-images.githubusercontent.com/24895255/81513205-df39df00-9350-11ea-8dab-def900143edc.png)
![Screen Capture_deepin-terminal_20200511062856](https://user-images.githubusercontent.com/24895255/81513206-dfd27580-9350-11ea-95a6-ffb5c8139c79.png)
![Screen Capture_deepin-terminal_20200511062930](https://user-images.githubusercontent.com/24895255/81513208-e06b0c00-9350-11ea-994a-80f1f7575edd.png)
![Screen Capture_deepin-terminal_20200511062954](https://user-images.githubusercontent.com/24895255/81513209-e103a280-9350-11ea-9aac-97dffead2015.png)
Mình đưa hình ảnh kết quả thực hiện các lệnh khi cài đặt, bạn xem giúp còn thiếu bước nào hay sai ở đâu giúp nhé. Thanhks!

**Comment by natsukagami** [comment]
Bạn cần phải có `$GOPATH/bin` ở trong `$PATH` để chạy được các tool được cài bằng `go install ...`. 

Ngoài ra bạn cần chuyển sang thư mục `frontend` để chạy `yarn dev` nhé.

**Comment by phuleethanh** [comment]
Cảm ơn bạn.
Khi thử với bản get từ docker (docker pull natsukagami/kjudge:latest) thì chạy được rồi. Không biết bản get từ docker này mình có thể Việt hóa lại được không ?

**Comment by natsukagami** [comment]
Hiện tại việc Việt Hoá kjudge bọn mình đang tìm cách cài đặt hợp lí nhất. Bạn vui lòng chờ trong 1 thời gian ngắn tới nhé!
