### ISSUE TITLE
Số lần submit

### ISSUE THREAD

**Issue by phuleethanh** [natsukagami/kjudge#24]
Chào bạn
Mình có thể chọn số lần user được phép submit theo mỗi bài được không ? Ví dụ Test có 5 bài tập, mỗi bài chỉ cho phép tối đa 2 lần nộp.

**Comment by natsukagami** [comment]
Tính năng này mới được cài đặt, bạn vui lòng chờ v0.7 sắp ra mắt nhé :+1:

**Comment by phuleethanh** [comment]
Cài bản mới mình dùng lệnh này luôn được không ?
docker pull natsukagami/kjudge:latest

**Comment by natsukagami** [comment]
Bạn có thể thử bằng cách thay `latest` bằng `unstable` nhé.
