### ISSUE TITLE
Limitation for contest name is too harsh

### ISSUE THREAD

**Issue by ngkan** [natsukagami/kjudge#43]
**Is your feature request related to a problem? Please describe.**
The current limitation for the contest name is 32 characters, which is not a good idea since the name of a contest can be much more longer. For example "Vietnamese National Olympiad in Informatics" has 43 characters already. 

**Describe the solution you'd like**
Increase the limit to 64 would be a fantastic solution.

**Describe alternatives you've considered**
Shortening the contest name but it is not always a good idea to do so.

**Comment by natsukagami** [comment]
Increasing the limit would be easy to do, but notice that a long contest name would make page titles very ugly to read.
