### ISSUE TITLE
Salt all passwords on the system

### ISSUE THREAD

**Issue by minhnhatnoe** [natsukagami/kjudge#88]
**Is your feature request related to a problem? Please describe.**

The function at https://github.com/natsukagami/kjudge/blob/be020e807c02c3dacc1ab283f2e3187a277bce7a/server/auth/password.go#L26 currently doesn't implement salting passwords.

**Comment by natsukagami** [comment]
[`bcrypt.GenerateFromPassword`](https://pkg.go.dev/golang.org/x/crypto/bcrypt#GenerateFromPassword) has salt built-in.
